[workspace]
members = [
    "crates/lib/kiri-runner",
    "crates/lib/kiri-common",
    "crates/lib/kiri-backend",
    "crates/lib/kiri-assets",
    "crates/bin/builder",
    "crates/lib/kiri-vfs",
    "crates/lib/kiri",
    "crates/lib/kiri-gfx",
    "crates/lib/kiri-resources",
    "crates/lib/kiri-render",
    "crates/lib/kiri-scene",
]

resolver = "2"
