[package]
name = "kiri-render"
version = "0.1.0"
edition = "2021"

[dependencies]
kiri-backend = { path = "../kiri-backend" }
kiri-common = { path = "../kiri-common" }
kiri-assets = { path = "../kiri-assets" }
kiri-gfx = { path = "../kiri-gfx" }
kiri-resources = { path = "../kiri-resources" }
kiri-scene = { path = "../kiri-scene" }
kiri-math = { path = "../kiri-math" }
thiserror = "1.0.61"
log = "0.4.20"
puffin = "0.19.0"
radsort = "0.1.1"

[features]
devel = ["kiri-assets/devel", "kiri-resources/devel", "kiri-scene/devel"]
