[package]
name = "kiri-backend"
version = "0.2.0"
edition = "2021"

[dependencies]
kiri-common = { path = "../kiri-common" }
arrayvec = "0.7.4"
ash = "0.38.0"
puffin = "0.19.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
log = "0.4.20"
byte-slice-cast = "1.2.2"
parking_lot = "0.12.3"
thiserror = "2.0.9"
byteorder = "1.5.0"
gpu-alloc = "0.6.0"
gpu-alloc-ash = "0.7.0"
rspirv-reflect = "0.9.0"
gpu-descriptor = "0.3.1"
gpu-descriptor-ash = "0.3.0"
