[package]
name = "kiri-gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
kiri-common = { path = "../kiri-common" }
arrayvec = "0.7.4"
ash = "0.38.0"
puffin = "0.19.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
log = "0.4.20"
gpu-alloc = "0.6.0"
gpu-alloc-ash = "0.7.0"
byte-slice-cast = "1.2.2"
parking_lot = "0.12.3"
bytes = "1.6.0"
glam = "0.28.0"
thiserror = "1.0.61"
rspirv-reflect = "0.8.0"
byteorder = "1.5.0"
uuid = "1.9.1"
bevy_tasks = { version = "0.14.0", features = ["multi_threaded"] }
