[package]
name = "kiri-resources"
version = "0.2.0"
edition = "2021"

[dependencies]
kiri-backend = { path = "../kiri-backend" }
kiri-common = { path = "../kiri-common" }
kiri-assets = { path = "../kiri-assets" }
kiri-vfs = { path = "../kiri-vfs" }
kiri-gfx = { path = "../kiri-gfx" }
kiri-math = { path = "../kiri-math" }
parking_lot = "0.12.3"
thiserror = "2.0.9"
log = "0.4.20"
arrayvec = "0.7.4"
bytes = "1.6.0"

[features]
devel = ["kiri-assets/devel", "kiri-gfx/devel"]
