[package]
name = "kiri-runner"
version = "0.2.0"
edition = "2021"

[dependencies]
kiri-common = { path = "../kiri-common" }
kiri-backend = { path = "../kiri-backend" }
kiri = { path = "../kiri" }
kiri-assets = { path = "../kiri-assets" }
kiri-gfx = { path = "../kiri-gfx" }
kiri-resources = { path = "../kiri-resources" }
kiri-math = { path = "../kiri-math" }
thiserror = "2.0.9"
directories = "5.0.1"
raw-window-handle = "0.6.2"
log = "0.4.22"
puffin = "0.19.0"
winit = "0.30.5"

[dev-dependencies]
simple_logger = "5.0.0"
puffin_http = "0.16.1"

[[example]]
name = "loop"

[features]
devel = ["kiri-assets/devel", "kiri-resources/devel", "kiri-gfx/devel"]
